version: 1
build:
  binary: vinced
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 100000000uatom
  - 100000000000000000000avince
- name: bob
  coins:
  - 5000000000000avince
faucet:
  name: bob
  coins:
  - 10avince
  host: 0.0.0.0:4500
host:
  rpc: ":26659"
  p2p: ":26658"
  prof: ":6061"
  grpc: ":9092"
  grpc-web: ":9093"
  api: ":1318"
genesis:
chain_id: "vinced_5000-1"
  app_state:
    crisis:
      constant_fee:
        denom: avince
    evm:
      params:
        evm_denom: avince
    gov:
      deposit_params:
        min_deposit:
        - amount: "10000000"
          denom: avince
    mint:
      params:
        mint_denom: avince
    staking:
      params:
        bond_denom: avince

validators:
- name: alice
  bonded: 100000000000000000000avince
  app:
    evm-rpc:
      address: 0.0.0.0:8545
      ws-address: 0.0.0.0:8546
  home: $HOME/.vinced
